### ISSUE TITLE
Error Undefined property

### ISSUE THREAD

**Issue by shmaltz** [5ally/my-custom-yourls#1]
Hi there, thanks again for writing this plugin. It works very well.
I have been getting this error in my logs: 
`PHP Notice:  Undefined property: stdClass::$code in /wp-content/plugins/my-custom-yourls/api.php on line 75`

**Comment by 5ally** [comment]
Hi @shmaltz

Sorry about that.. 😁 and I'll fix that later today or tomorrow.

But I'm just wondering if you're already using [YOURLS v1.9](https://github.com/YOURLS/YOURLS/releases/tag/1.9)?

**Comment by shmaltz** [comment]
Hi @5ally,

I just tested v1.9 and it seems the links are not getting created at all.

**Comment by 5ally** [comment]
Hi @shmaltz,

Sorry for the delay, we've got frequent power supply disruption recently.

So please check the recent commits and manually update your copy of the plugin (but the main file really just had 1 tiny update - the Version line).

**Comment by 5ally** [comment]
> Hi @5ally,
> 
> I just tested v1.9 and it seems the links are not getting created at all.

Maybe you forgot to change your API settings in the main plugin file?

Because I tested with WordPress v5.9.3 and everything worked well for me.

**Comment by shmaltz** [comment]
@5ally  Thanks for the quick fix! For some reason the API key changed when updating to the new version. Never happened before. Everything works great now.
